# for train
pretrain: https://vocr.vn/data/vietocr/vgg_seq2seq.pth

# url or local path (for predict)
weights: https://vocr.vn/data/vietocr/vgg_seq2seq.pth

backbone: vgg19_bn
cnn:
    # pooling stride size
    ss:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]         
    # pooling kernel size 
    ks:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]
    # dim of ouput feature map
    hidden: 256

seq_modeling: seq2seq
transformer:
    encoder_hidden: 256
    decoder_hidden: 256
    img_channel: 256
    decoder_embedded: 256
    dropout: 0.1

optimizer:
    max_lr: 0.001
    pct_start: 0.1
