pretrain: 
    id_or_url: 13327Y1tz1ohsm5YZMyXVMPIOjoOA0OaA
    md5: fbefa85079ad9001a71eb1bf47a93785
    cached: /tmp/tranformerorc.pth

# url or local path
weights: https://drive.google.com/uc?id=13327Y1tz1ohsm5YZMyXVMPIOjoOA0OaA

backbone: vgg19_bn
cnn:
    # pooling stride size
    ss:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]         
    # pooling kernel size 
    ks:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]
    # dim of ouput feature map
    hidden: 256

seq_modeling: convseq2seq
transformer:
    emb_dim: 256
    hid_dim: 512
    enc_layers: 10
    dec_layers: 10
    enc_kernel_size: 3
    dec_kernel_size: 3
    dropout: 0.1
    pad_idx: 0
    device: cuda:1
    enc_max_length: 512
    dec_max_length: 512
